### ISSUE TITLE
Output table values

### ISSUE THREAD

**Issue by michoug** [chengsly/DeepMicrobeFinder#1]
Hi,
Nice tool,
I wanted to know if you are considering a minimum threshold under which the contig/sequence will not be assigned to any category?
Best
Greg

**Comment by housw** [comment]
Hi Greg, 

thanks for your interest in our software, currently we don't have such a threshold and it might be tricky to give one. You can filter the prediction table according to your own rules, it's a TSV file.

Cheers, 
Shengwei
