### ISSUE TITLE
predict.py fails with "TypeError: unsupported operand type" for length parameter

### ISSUE THREAD

**Issue by johnbullard-uf** [chengsly/DeepMicrobeFinder#2]
https://github.com/chengsly/DeepMicrobeFinder/blob/7d05b2c0055ec3a8fbf8766fa7213d0ef70b46e1/predict.py#L19

The "length" parameter in the above referenced line is set to `type="string"` which causes failures in the predict_single() function when it tries to use that string for math functions:

```
Step 2/3: Encode and predict...
Traceback (most recent call last):
  File "/apps/deepmicrobefinder/20210731/repo/predict.py", line 203, in <module>
    score = predict_single(seq, options.modelLength)
  File "/apps/deepmicrobefinder/20210731/repo/predict.py", line 149, in predict_single
    count_iter = seqLength / length
TypeError: unsupported operand type(s) for /: 'int' and 'str'
```

**The length parameter should be set to `type="int"`.**

**Comment by chengsly** [comment]
fixed in latest commit for predict.py
