### ISSUE TITLE
predict.py file and encoding_model not found

### ISSUE THREAD

**Issue by SaraiFinks** [chengsly/DeepMicrobeFinder#5]
I am really excited to try out DeepMicrobeFinder on some soil MAGs, but unfortunately I encountered an issue after successfully following the conda installation instructions, with running the program. I got an initial error message that predict.py file was not found, after adding it to my working directory, I get the following error message:

Using TensorFlow backend.
Traceback (most recent call last):
  File "predict.py", line 4, in <module>
    from encoding_model import EncodingScheme
ModuleNotFoundError: No module named 'encoding_model'

Were these files/modules suppose to be installed when following the conda installation instructions?  Any help/tips to get DMF installed and working proper would be much appreciated, thanks!

**Comment by chengsly** [comment]
hello, thanks for the interest. could you try running: 

python predict.py -i test.fasta -e one-hot -d models/one-hot-models/ -m hybrid

and see if it works? right now we need to run the predict.py script in the same directory for it to work.

**Comment by SaraiFinks** [comment]
Hey, thanks for the help! I ended up cloning the DMF repo and adding it to my working directory with the files and now it appears to be running (fingers crossed). Trying it out on MAGs from one soil sample for now (~1.2 GB), any guess on how long this should take to run, single node, 32 cores, mem-per-cpu 4G. Also, sorry for the naive question, and without looking under the hood at all the code, are the results for each prediction (Prok, ProkVir, Euk, EukVir) outputted to separate directories? Thanks again for the help.

**Comment by SaraiFinks** [comment]
Hi! Thank you very much for you help. Okay I tried running what you mentioned and got the following outputs. Does this look correct to you?
<img width="1021" alt="Screen Shot 2021-11-13 at 11 27 22 AM" src="https://user-images.githubusercontent.com/39506567/141656648-63ba7157-a9bd-4053-a473
<img width="794" alt="Screen Shot 2021-11-13 at 11 28 03 AM" src="https://user-images.githubusercontent.com/39506567/141656661-2b53b764-b359-4394-afcf-32c01c90b8f5.png">
-d75aeb3e2d9c.png">
<img width="802" alt="Screen Shot 2021-11-13 at 11 28 32 AM" src="https://user-images.githubusercontent.com/39506567/141656672-56355241-918c-4f16-82d9-75aa55d9ec3e.png">

**Comment by SaraiFinks** [comment]
Also, this is what the prediction results look like:)
<img width="1007" alt="Screen Shot 2021-11-13 at 11 29 49 AM" src="https://user-images.githubusercontent.com/39506567/141656706-51c45042-5315-4c63-bb80-42dd13c2f289.png">

**Comment by SaraiFinks** [comment]
I tried it out a small sample of soil MAGs and it appears to work perfectly, thanks!!
